// BACKEND DISABLED - Frontend only with mock data
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Supabase connection is disabled - using mock data only
// const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Export a mock client to prevent errors
// All data queries are handled by useSpecies hooks using local mock data
export const supabase = createClient<Database>(
  "https://placeholder.supabase.co",
  "placeholder-key",
  {
    auth: {
      storage: localStorage,
      persistSession: false,
      autoRefreshToken: false,
    },
  }
);
